services:
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: app/Dockerfile
    ports:
      - "8000:80"
    depends_on:
      - db
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB=postgres

    # guarda os arquivos da raiz do projeto no diretório "app" do container (ele aplica a mudança instantanemente e não precisa rebuildar, ideal para desenvolvimento)
    volumes:
      - .:/app

  db:
    container_name: database
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES: postgres

  adminer:
    container_name: adminer
    image: adminer
    ports:
      - "8080:8080"

    # guarda os dados na pasta "data" do postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

# cria volume externo pra guardar os dados
volumes:
  postgres_data:
