services:
  backend:
    container_name: api
    build:
      context: .
      dockerfile: app/Dockerfile
    ports:
      - "8000:80"
    depends_on:
      - db
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB=postgres
    networks:
      - rede_local

  db:
    container_name: database
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES: postgres

    # guarda os dados na pasta "data" do postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

    networks:
      - rede_local

  adminer:
    container_name: adminer
    image: adminer
    ports:
      - "8080:8080"

# cria volume externo pra guardar os dados
volumes:
  postgres_data:

networks:
  rede_local:
    driver: bridge